global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    clusterArn: arn:aws:eks:us-west-2:343039485463:cluster/plt-or-prod-main-eks-0
    environment: production

remote_write:
  - url: "https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-31bda848-4304-47fb-81f9-7168b4374a5d/api/v1/remote_write"
    sigv4:
      region: "us-east-1"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

scrape_configs:
  - job_name: pod_exporter
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod

  - job_name: cadvisor
    scheme: https
    authorization:
      credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
      - source_labels: [__name__]
        regex: "container_cpu_usage_seconds_total|container_memory_usage_bytes"
        action: keep

  - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    job_name: kubernetes-apiservers
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - action: keep
        regex: default;kubernetes;https
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_service_name
          - __meta_kubernetes_endpoint_port_name
      - source_labels: [__name__]
        regex: "apiserver_request_total|apiserver_response_sizes"
        action: keep # Retain only key API server metrics
    scheme: https

  - job_name: kube-proxy
    honor_labels: true
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: keep
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_name
        separator: "/"
        regex: "kube-system/kube-proxy.+"
      - source_labels:
          - __address__
        action: replace
        target_label: __address__
        regex: (.+?)(\\:\\d+)?
        replacement: $1:10249
      - source_labels: [__name__]
        regex: "kubeproxy_sync_proxy_rules_latency_seconds"
        action: keep # Keep only important kube-proxy metrics
