image: hashicorp/terraform:0.12.31

pipelines:
  pull-requests:
    '**':
      - parallel:
          - step:
              name: Check format
              script:
                - terraform fmt -diff=true -check=true
          - step:
              name: Validate
              script:
                - ./validate.sh
