{
 "title": "Application",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Successful API Calls",
   "type": "graph",
   "description": "How many calls is the api serving successfully?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Calls/Minute" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service,grpc_method) (increase(grpc_client_handled_total{grpc_code=\"OK\",job!=\"kubernetes-apiservers\"}[1m]))",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Failed API Calls",
   "type": "graph",
   "description": "How many API calls are failing?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Failures/Minute over 2m" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service,grpc_method,grpc_code) (increase(grpc_client_handled_total{grpc_code!=\"OK\",job!=\"kubernetes-apiservers\"}[1m]))",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}/{{grpc_code}}"
    }
   ]
  },
  {
   "title": "API Response Times",
   "type": "graph",
   "description": "How long does the oracle take processing API requests?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s", "label": "97th percentile over 5m" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.97, sum(rate(grpc_client_handling_seconds_bucket[5m])) by (le, grpc_method, grpc_service))",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Phylum Response Times",
   "type": "graph",
   "description": "How long does the chaincode take processing requests (including time spent ordering and committing transactions)?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms", "label": "97th percentile over 5m" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.97, sum(rate(shirogateway_tx_dur_bucket[5m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "graph",
   "description": "What errors have been logged?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Entries/Minute" }
   ],
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_component,message) (increase(log_statements_message{level=\"error\"}[1m]))",
     "legendFormat": "{{app_kubernetes_io_component}}/{{message}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "How many open file descriptors do services have?",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{app_kubernetes_io_part_of=~\".+\",app_kubernetes_io_part_of!=\"fabric\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_name}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "description": "How much memory are off-chain components using?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{app_kubernetes_io_part_of=~\".+\",app_kubernetes_io_part_of!=\"fabric\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_name}}/{{instance}}"
    }
   ]
  }
 ]
}