{
 "title": "Fabric",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Peer Logging",
   "type": "graph",
   "description": "How many errors are fabric peers logging?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Logs/Minute over 2m" }
   ],
   "targets": [
    {
     "expr": "sum by (level) (rate(logging_entries_written{app_kubernetes_io_component=\"bcpeer\"}[2m])) * 60",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Orderer Logging",
   "type": "graph",
   "description": "How many errors are fabric orderers logging?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Logs/Minute over 2m" }
   ],
   "targets": [
    {
     "expr": "sum by (level) (rate(logging_entries_written{app_kubernetes_io_component=\"bcord\"}[2m])) * 60",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Endorsement Duration",
   "type": "graph",
   "description": "How long are transactions taking to endorse?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, endorser_propsal_duration_bucket)",
     "legendFormat": "{{app_kubernetes_io_instance}}/{{chaincode}}/{{success}}"
    }
   ]
  },
  {
   "title": "Blockchain Height",
   "type": "graph",
   "description": "How many blocks exist according to each component?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ledger_blockchain_height{channel=\"luther\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  }
 ]
}