{
 "title": "K8s Workers",
 "description": "High level metrics for k8s workers (nodes)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Network Utilization",
   "type": "graph",
   "description": "How much network traffic is going through k8s workers?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_node) (rate(node_network_receive_bytes_total[5m]))",
     "legendFormat": "rx{kubernetes_node={{kubernetes_node}}}"
    },
    {
     "expr": "sum by (kubernetes_node) (rate(node_network_transmit_bytes_total[5m]))",
     "legendFormat": "tx{kubernetes_node={{kubernetes_node}}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "How much CPU are the k8s workers using?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (kubernetes_node, cpu) (irate(node_cpu_seconds_total{job=\"kubernetes-service-endpoints\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{kubernetes_node}}/{{cpu}}"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "description": "How much memory are k8s workers using?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent", "label": "% Used" }
   ],
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod!=\"\", container!=\"\", container!=\"POD\"}[5m])) by (pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Container Working Set Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory Usage (bytes)" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod!=\"\", container!=\"POD\", container!=\"\"}) by (pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "graph",
   "description": "How many pods are on each k8s worker?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "# of pods" }
   ],
   "targets": [
    { "expr": "kubelet_running_pods", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "EBS Volume Utilization",
   "type": "graph",
   "description": "How full are the EBS volumes attached to k8s pods?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent", "label": "% Full" }
   ],
   "targets": [
    {
     "expr": "(1 - kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes) * 100",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Root Volume Utilization",
   "type": "graph",
   "description": "How full are the k8s worker root volumes?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent", "label": "% Full" }
   ],
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  }
 ]
}